### ISSUE TITLE
Airgap Vault on Android OS

### ISSUE THREAD

**Issue by amerek1** [airgap-it/airgap-vault#100]
Airgap vault deleted all secrets and will not allow me to confirm secrets.  The confirm button, although activated, is not responsive.

**Comment by amerek1** [comment]
This is on a Samsung Galaxy 7 with the latest version of Android OS.  I will just switch to a different wallet, seems like this is a chronic issue with the Airgap platform.

**Comment by AndreasGassmann** [comment]
There was a bug in the previous version, but we released a hotfix that fixes this issue. Could you let me know what version of the app you were using?

**Comment by mlaeng** [comment]
closed due to inactivity
