### ISSUE TITLE
Missing storage permission on Android 5.1 (API Level 22)

### ISSUE THREAD

**Issue by tolbrino** [airgap-it/airgap-vault#11]
When launching the app the following error is shown: `The connection to the server was unsuccessful. (file ///android_asset/www/index.html)`. I suspect this is due to the missing permission. Following that the app is shut down, thus not usable.

**Comment by pascuin** [comment]
@tolbrino Could you let us know which device you're using and which Android version? Also did you have a version installed before or is this a first install?

**Comment by tolbrino** [comment]
Device: Moto G
Android Version: 5.1

And it was a first install of the app.

**Comment by tolbrino** [comment]
Any update on this?

**Comment by venomega** [comment]
Huawei Y6II says same thing
Android 6 rooted
![Screenshot_2020-01-04-22-39-17](https://user-images.githubusercontent.com/41645647/71774822-788c5b00-2f43-11ea-8d85-6b45d0a0a59c.png)

**Comment by AndreasGassmann** [comment]
We have just released a new version that includes some big internal changes. One of them is the move from `cordova` to `capacitor`. This means that a lot of the native code and how the webview is loaded is different.

Could you please give it another try and let us know if the problem persists?

**Comment by AndreasGassmann** [comment]
I will close this issue because the app has changed a lot since this issue was created. Feel free to re-open if the problem persists in the latest version.
