### ISSUE TITLE
Don´t know AirGap Vault "default" secret

### ISSUE THREAD

**Issue by EthraZa** [airgap-it/airgap-vault#110]
I have this "old" Xiaomi Android 10 phone, I just factory reset and install AirGap Vault.
So, I have generated and written down the 24 words. As soon as I confirmed the passphrase, it throued a "Verify Your Identity" black screen on me. It doesn't accept my Android password or my just created AirGap passphrase, so I don´t know what this secret is since I just reseted the phone and didn't even login to a Google account since it is an offline phone now.
Then I killed the "Config. secret screen" and the AirGap Vault app. Now when I reopen the AirGap app it shows the black screen rightway and if I kill it again, it shows the AirGap first screen indicating my previously created wallet is probably gonne.
So I uninstalled the AirGap Vault and reinstalled it. Choose the Import option, enter the 24 words and as soon as I enter my passphrase, the secret black screen is back.
I really don't know how to bypass this secret that is not mine. So, I appreciate any hint on how to proceed.
FYI, I have installed Electrum on this phone too and it is working properly, no unknown secret screen.

**Comment by EthraZa** [comment]
Hi, thank you for answer. I used your test to try harder and found out what was happening.

I don't need to go all the steps to see the password screen, in the meedle of step 3, if I go to home and come back to the app it will ask the password.
So, this time, I noticed that when I enter my Android password the screen would "blink", allowing me to see the AirGap screen for a split second, and that was the hint. The Android password was working, but it was asking the password again. I enter the password again and it works. But every time I enter the app, it will ask the password again.
I put a long and complex password in this phone, so when it ask it twice, it is easy to enter the password wrong one time or another, so it will probably start over to ask it twice (not sure) and then will seems like it is not working.

Anyways you helped me to find out the problem and now I can start the real test phase.
Thank you.

**Comment by humbkr** [comment]
I have the same issue on a Moto G5 (android 8), the app is indeed asking the phone password multiple times.
It's really confusing, I couldn't figure out what was happening before finding this issue.

**Comment by AndreasGassmann** [comment]
Thank you both for responding. This is interesting, so it seems that it is related to the native authentication.

If you enter it multiple times, does it work at some point, or does it ask you for the password forever?

We will look into this, but due to the holidays it might take a bit longer, sorry for the inconvenience.

**Comment by EthraZa** [comment]
For me it seems to be asking 2 or 3 times in a row in some place and just 1 at other times - like, when we switch to another app and comeback is just 1. But in the wallet creation, it is always 2 or 3 times.
