### ISSUE TITLE
BIP39 Passphrase import

### ISSUE THREAD

**Issue by pjw65** [airgap-it/airgap-vault#115]
When I enter CAN, the app takes that and goes to the next word.
But there are 3 possibilities: CAN, CANAL, CANCEL.
The app should not automatically take CAN and wait for a selection of one of the three.
Workaround click on the alread selected word CAN and select one of the others.

There are possible other 3-character words that behave alike.

**Comment by AndreasGassmann** [comment]
This bug has already been fixed and merged to develop. It will be included in the next release.
