### ISSUE TITLE
Metamask Signature error on QR-code read 

### ISSUE THREAD

**Issue by rafaeloliva06** [airgap-it/airgap-vault#119]
Integration with vault and metamask went smoothly, reading QR-codes in transactions also works without problems, but in Dapps that ask for "Signature Request", like opensea's "create" option, or login in many other Dapps does not work correctly, the following error appears when I try to read the QR-code 
"**Incompatible code**  
Could not parse code. Please make sure this is a valid AirGap code. You can try to handle this code in AirGap Wallet by using the "Relay" button below."

![image](https://user-images.githubusercontent.com/32191344/151296694-52bc465e-827d-4c41-b646-460838bdc805.png)

**Comment by AndreasGassmann** [comment]
Hi. Thank you for the report.

AirGap Vault does currently not support arbitrary message signing for Ethereum. We're already working on this and have an internal version that adds support for it, which we are currently testing. If all goes well, it should be released early next week.

**Comment by rafaeloliva06** [comment]
Thanks for the reply, I'll be waiting for this update :)

**Comment by AndreasGassmann** [comment]
Version `3.14.0` is currently being reviewed by the stores and should be available shortly.
