### ISSUE TITLE
Startup check failed disclaimerAcceptedCheck 

### ISSUE THREAD

**Issue by etharner** [airgap-it/airgap-vault#12]
I've built master branch and it looks like AirGap Vault must be reopened once after opening at first time to accept disclaimer, for example it doesn't allows me to sign transaction until I reopen it.

![image](https://user-images.githubusercontent.com/7098449/62464683-99078c00-b7d0-11e9-8a3d-1b9fa0fdbbae.png)

**Comment by etharner** [comment]
Also it worth mentioning that sometimes it doesn't do anything even without this error when I open Vault through deeplink from Base Aepp. After restarting Vault it works.

**Comment by AndreasGassmann** [comment]
Hi, thanks for the report.

I was able to reproduce the error and will let you know when I find out more.

**Comment by AndreasGassmann** [comment]
The issue was fixed a long time ago.
