### ISSUE TITLE
qr scanning scaling issue

### ISSUE THREAD

**Issue by zoneamick** [airgap-it/airgap-vault#135]
Hello,
on an older device with a resolution of 720x1280 

I got a scaling issue at the bottom where i can not completely scroll down to get a complete qr scan.

![Inked](https://user-images.githubusercontent.com/11229853/164081782-59b80c8a-4c68-4aed-ba35-55685cfba8b4.jpg)

thanks

**Comment by AndreasGassmann** [comment]
Thanks for the report. A fix for this should be included in the next release
