### ISSUE TITLE
Not working on Samsung Galaxy S4

### ISSUE THREAD

**Issue by babhong** [airgap-it/airgap-vault#136]
Hi, I have a Samsung Galaxy S4, and AirGap Vault doesn't seem to work on it. I have updated Android System Webview. Have updated Chrome as well. The phone is running stock OS. When I open AirGap Vault, it just gets stuck on the loading screen, with the white background and the AirGap logo. When I I leave the app and the screen goes dark, though — when I come back and wake the phone, I can briefly see the setup screen that I'm supposed to see — but it's very brief, and then the loading screen comes back, and I'm stuck there again.

**Comment by debeldami** [comment]
Samsung S4 does not meet the [minimum requirement for AirGap](https://support.airgap.it/FAQ#what-version-of-android-os-supports-the-airgap-wallet-and-vault). I will close this issue.
