### ISSUE TITLE
unreproducible according to walletscrutiny

### ISSUE THREAD

**Issue by aborilov** [airgap-it/airgap-vault#143]
Hey!
https://walletscrutiny.com/iphone/it.airgap.vault/
saw in history that build were reproducible, but in latest build, it's not

**Comment by AndreasGassmann** [comment]
The link you included points to the iPhone version. iOS apps are very hard (maybe impossible?) to properly reproduce and there is currently no iOS app that can be reproduced.

The issues around android reproducibility are tracked here: https://github.com/airgap-it/airgap-vault/issues/127
