### ISSUE TITLE
Bug - shown wrong Coin name when dealing with MetaMask

### ISSUE THREAD

**Issue by NawarKh** [airgap-it/airgap-vault#151]
First of all, thanks for the nice work
After trying it out with
MetaMask
Airgap vault  in andorid
Metamask in Iphone
and according to " but the AirGap Vault is blockchain agnostic. It can sign transactions on any EVM chain by adding the RPC of that chain to MetaMask "

When sending BNB from Metamask and during the transmission authentication process
Show currency name
ethereum
With the BNB transfer

the transfer was successful and there is no problem
Only the name of the currency causes the sender some doubt, especially the difference between their price
![AAAAA](https://user-images.githubusercontent.com/63479836/181249736-093b19b0-5046-4ef7-9e86-6fb9c128c7c3.jpeg)

Thanks

**Comment by AndreasGassmann** [comment]
The only information the Vault has is the chainID to differentiate the different chains. We can probably add some of the well known chainIDs and map them to specific names and then show no name for the others.

Thanks for the suggestion, we will look into this for one of the next releases.

**Comment by debeldami** [comment]
As Andreas mentioned, the only information the Vault has is the chainID. So, it is unable to tell the sticker of the blockchain it's dealing with. In the future, we might consider hardcoding specific stickers to different chains. I will close this issue because it is old.
