### ISSUE TITLE
Unable to withdraw USDC with BIP-39 issue

### ISSUE THREAD

**Issue by luyotw** [airgap-it/airgap-vault#153]
I want to withdraw my USDC on Ethereum from my AirGap Wallet, but when signing the transaction, the AirGap Vault app told me "If you have set a BIP-39 passphrase, please enter it here.", I'm pretty sure I have never set that, so I press "Ok" directly with leaving it empty, then it showed "Public keys do not match. Did you enter the correct BIP-39 Passphrase?".

I can withdraw ETH with the same secret without the app having me to enter that. I've checked the error history, the error message was "Uncaught (in promise): Error: not Implemented".

Is there anything I did wrong? I can't even exchange USDC to other tokens for the same issue, so my USDC have been trapped in the wallet, what can I do?

**Comment by luyotw** [comment]
![截圖 2022-08-08 下午3 58 20](https://user-images.githubusercontent.com/47925706/183369045-a0b5db7c-3bdf-43b0-a0c1-d01f6c921f9e.png)

**Comment by AndreasGassmann** [comment]
The bug where you cannot send certain ERC20 tokens has been fixed a few days ago and will be included in the next release.

You can either wait for the fix to be released to send your USDC, or you can pair your Vault to MetaMask. If you initiate the USDC transaction with MetaMask, then it should work. (Tutorial: https://support.airgap.it/guides/metamask)

Sorry for the inconvenience.

PS: The "Error: not implemented" error is not related to it, it happens every time you start the app.

**Comment by luyotw** [comment]
@AndreasGassmann I see, thank you so much!
