### ISSUE TITLE
Ssd news coin

### ISSUE THREAD

**Issue by al594** [airgap-it/airgap-vault#154]
is it possible to add monero or zcash?  it's just that very few multi-coin wallets support them, so I would be very happy if you add these coins.  and also, I tried to download a client for windows or Linux, but it gives out a repository with an .APK file for android.

**Comment by AndreasGassmann** [comment]
In theory, both Monero and ZCash could be added to AirGap. Sadly, we currently don't have the resources to work on those protocols. If someone would create a PR to integrate them, we would happily merge it.

There should be a linux version available in the GitHub Actions artifacts. But we don't officially support AirGap Vault desktop versions.
