### ISSUE TITLE
Support Legacy transaction

### ISSUE THREAD

**Issue by heisenberg-2077** [airgap-it/airgap-vault#157]
Currently when using Rabby and Airgap Vault, legacy transactions are sent by default. But now Airgap Vault does not support processing legcay transaction data. Do you have plans to support?
 
https://github.com/RabbyHub/Rabby/issues/924

**Comment by AndreasGassmann** [comment]
If I remember correctly, we do not handle legacy transactions because MetaMask only uses the newer format as far as I know.

We could look into supporting legacy transactions, but is there a reason why Rabby uses legacy transactions by default?

**Comment by heisenberg-2077** [comment]
The default legacy transaction is for compatibility. 
Because Rabby supports many kinds of hardware wallets, some wallets do not support eip-1559 when the version is too low.

**Comment by AndreasGassmann** [comment]
As far as I'm aware, the only QR based signers are KeyStone and AirGap Vault. Both of which support EIP-1559. Would it be possible to change the default for QR based HW wallets to EIP-1559?

We can look into supporting legacy transactions, but ideally we should try to move the default to the newer standards.
