### ISSUE TITLE
[Suggestion] Ethereum staking derivatives

### ISSUE THREAD

**Issue by OneAndNobody** [airgap-it/airgap-vault#159]
Hi. It would be great if the app supported Ethereum staking tokens such as RocketPool's rETH and Lido's stETH.

**Comment by AndreasGassmann** [comment]
I'm assuming this issue is related more to AirGap Wallet. You can already interact with any ERC20 token if you pair AirGap Vault with MetaMask, which is our recommended approach for advanced users.

**Comment by OneAndNobody** [comment]
Thanks for the reply, I wasn't aware of this.
