### ISSUE TITLE
Does not support Optimism Mainnet

### ISSUE THREAD

**Issue by dddd2022** [airgap-it/airgap-vault#161]
Cant sign Optimism tx from metamask.

**Comment by AndreasGassmann** [comment]
Could you please provide more information about what you tried to do and what failed? We did a transaction on testnet and it worked.

**Comment by rswxfy** [comment]
Incompatible code

Could not parse code. Please make sure this is a valid AirGap code. You can try to handle this code in AirGap Wallet by using the "Relay" button below.

**Comment by dddd2022** [comment]
> Could you please provide more information about what you tried to do and what failed? We did a transaction on testnet and it worked.

all tx on Optimism cant be signed.
for example, sending 0 eth to myself.

version
airgap vault 3.18.0
metamask 10.19.0

err msg
```
Incompatible code

Could not parse code. Please make sure this is a valid AirGap code. You can try to handle this code in AirGap Wallet by using the "Relay" button below.

**Comment by debeldami** [comment]
Optimism QR code now works, so I will close this issue.
