### ISSUE TITLE
Enumeration of BIP39 words are different than the standard

### ISSUE THREAD

**Issue by AndresChapo** [airgap-it/airgap-vault#166]
I used BIP39 words list on AirGap vault to pass my seed phrase to numbers so I could write them in a steel wallet.
Then I realize that other websites like the [bitcoin repo](https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt), [getcoinplate](https://getcoinplate.com/blog/official-bip39-word-list-mnemonic-in-english-verified/), [Blockplate](https://www.blockplate.com/pages/bip-39-wordlist) (the first 3 sites when you google "BIP39 words list"), starts counting with 1 = abandon, when the AirGap starts with 0 = abandon .
<img width="201" alt="image" src="https://user-images.githubusercontent.com/11888868/203210689-f4954887-31be-4bc6-9438-3c3ebeeabcf5.png">
<img width="201" alt="image" src="https://user-images.githubusercontent.com/11888868/203210748-98d40965-f976-4598-a205-bb33d5f11791.png">

I know it doesn't look like a big thing. But actually I was preparing that steel wallet to inherit it in case I pass away. so the person who will try to get back the words wouldn't find the right seed phrase.

I guess the solution would be some kind of advice in the app, or a switch button to see it the other way.

**Comment by AndreasGassmann** [comment]
Hi, thanks for reporting this issue. I think our list starts from 0 simply because we iterate over the array of words and arrays start at 0. But you are right, we should be consistent with the other lists, so we'll change that.

If you want, you can create a PR for it and we will merge it, otherwise I'll add it to our backlog.

**Comment by AndresChapo** [comment]
Nice!
How can I submit a PR? I mean, I don't have permission for that.

**Comment by AndreasGassmann** [comment]
> Nice!
> 
> How can I submit a PR? I mean, I don't have permission for that.

Hey, sorry, I'm just seeing this now.

To create a PR, you don't need any special permissions. You can basically just fork the repository and do the changes in our own repository, then create a PR to merge your changes into the main repository.

Let me know if you need any more help with this!

**Comment by mlaeng** [comment]
This has been changed in one of the last versions. I'll close this issue. Thanks for pointing it out!

![image](https://user-images.githubusercontent.com/1638365/218515873-e28d9fa1-d0c7-4823-bdb9-0127965f0a05.png)
