### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by swedebugia** [airgap-it/airgap-vault#17]
Could you please add one?

**Comment by AndreasGassmann** [comment]
Hi, we still haven't decided on a license. We will update this ticket once we do: https://github.com/airgap-it/airgap-wallet/issues/2

**Comment by AndreasGassmann** [comment]
I'm happy to tell you that both apps, [AirGap Wallet](https://github.com/airgap-it/airgap-wallet/blob/master/LICENSE.md) and [AirGap Vault](https://github.com/airgap-it/airgap-vault/blob/master/LICENSE.md) are now `MIT` licensed! 🙂 

@swedebugia
