### ISSUE TITLE
Scanner doesn't work || Huawei P10 Lite || 3.19.0

### ISSUE THREAD

**Issue by Valadramuz** [airgap-it/airgap-vault#174]
Huawei P10 Lite | Fabric Data Restored

Airgap Vault 3.19.0

Installation method via: APK

Scanner doesn't work

Uncaught (in promise): TypeError:
Cannot read property 'emod' of undefined
TypeError: Cannot read property
"emod' of undefined
at getNgModuleDef

![Error](https://user-images.githubusercontent.com/100401499/211230228-1555c9a8-ceb3-423e-bad6-f546067f93a6.jpg)

**Comment by Valadramuz** [comment]
I cannot use my 'Vault' phone to sign transactions on the 'Wallet' phone.

**Comment by mlaeng** [comment]
Hey! Sorry this has happened. Can you describe step by step what you did, where it failed and how it failed? I am assuming you were clicking the scan button and then the scanner or camera did not come up, but I might be wrong. Pls explain...

**Comment by Musashi25** [comment]
Hello, exactly the same problem. I installed Airgap Vault on a Samsung Galaxy S7 (Android 8) by the APK method available on Github. On versions prior to 28519, everything works but no compatibility with Metamask. On the following versions, the installation works but no access to the scanner. The camera does not open, so you cannot scan a qr code. Strangely, the application has access to the camera when generating the seed.

**Comment by Musashi25** [comment]
v3.7.0 is the latest version that works with the scanner. The following versions install but the scanner does not work.

**Comment by mlaeng** [comment]
At one point in the past we had the issue that when scanning for an address, the camera picture would not show, but if you point it to the QR code, the address would still be successfully scanned. Did you try this - just for us to make sure it's not this problem?

**Comment by Musashi25** [comment]
With version 3.19.0 (and all versions beyond 3.7.0) the scanner button doesn't launch anything at all. I made a little video for more understanding.

https://user-images.githubusercontent.com/120664477/218524918-eca57b94-5119-421a-aac0-949595075317.mp4
