### ISSUE TITLE
Missing text, labels in Vault

### ISSUE THREAD

**Issue by wacher74** [airgap-it/airgap-vault#182]
First steps of setup were succesful, but just happend this:

![20230214_210953134_iOS](https://user-images.githubusercontent.com/24725150/218866663-34f8e6ff-f211-46bf-bc52-ef68ad761e2f.jpg)
![20230214_211031875_iOS](https://user-images.githubusercontent.com/24725150/218866666-0e46dc43-6c10-4fd6-8289-7378d64c30d1.jpg)
![20230214_211136104_iOS](https://user-images.githubusercontent.com/24725150/218866667-bce6c845-68aa-4f8d-a1aa-3adb689330f3.jpg)
![20230214_211514003_iOS](https://user-images.githubusercontent.com/24725150/218866671-48743fa6-6b50-4743-9b95-dcdeb2c6cfed.jpg)

Version 3.23.0 (build 49376)
iPhone 8, iOS 16.3

**Comment by mlaeng** [comment]
@wacher74 Hey! There's an issue with the default language (depending on you phone's default language) where the fallback to english is failing if we don't support your default language. You can fix it by going to settings and set the preferred language manually to english. But you need at least one secret generated or imported to be able to access the settings page.

**Comment by wacher74** [comment]
Okay, this helped me.
But if the application doesn't support my language, why doesn't fallback to english automaically?
