### ISSUE TITLE
apk 3.23.1 has broken labels

### ISSUE THREAD

**Issue by zamrokk** [airgap-it/airgap-vault#186]
The last Android version has variable names everywhere instead of human readeable labels. Something should have been broke on the code :/

**Comment by mlaeng** [comment]
@zamrokk we are aware of it. It's a bug in the fallback that should always display english if the currently set default language is not available. for now you can manually select english in the settings to fix that.

**Comment by zamrokk** [comment]
Ok 😎

Le jeu. 23 févr. 2023 à 08:16, Markus Laeng ***@***.***> a
écrit :
