### ISSUE TITLE
Scan this (address) QR code with Metamask does not work

### ISSUE THREAD

**Issue by SvenMeyer** [airgap-it/airgap-vault#188]
1) I wanted to send funds from Metamask (v10.25.0 on Chrome) on Linux Desktop to an account in Airgap-Vault.

- MM : send ETH
- MM : for address selection chose [scan QR code]
- Airgap-Vault : [show QR code]
- MM : open camera ... scanning => ERROR

I notided that the camera image is mirrored, but even after I mirrored the Airgap-Vault QR-code it did not work.
Chosing QR code v2 or v3 on Airgap-Vault does not work either.

-------------------------------------------------------------

2) Note : The other direction worked 
- initiating a tx on metamask, create QR code of tx
- scan & sign tx with AirGap-Vault
- MM scan the signed tx as QR code

**Comment by mlaeng** [comment]
The Airgap vault is only to manage secrets. To manage funds, you would have to install the Airgap Wallet app (either on the same device or a different device) If you use the Airgap Wallet app, you can derive an ETH address from the secret in your vault. You will then see that account/address in Airgap Wallet. If you tap on it you will see a "receive" button and if you tap on that, the address QR code will be displayed. This is the one you would scan with Metamask.

**Comment by SvenMeyer** [comment]
I just installed AirGap Vault 3.25.0

1) Is actually pretty easy. I can just use : [Menu] > [Show Address QR] .. scan it with Metamask (laptop webcam)

2) I just tried this with Optimism network, expecting that every EVM chain should behave pretty identical, and Metamask would just send the signed transaction to another chain / RPC node ... however I got an error within AirGap Vault when trying to scan the Metamask QR-code of the transaction.

**Comment by mlaeng** [comment]
@SvenMeyer in the meantime Optimism should be supported as well. Make sure you get the latest version. I'll close this issue...
