### ISSUE TITLE
Request to add support for Avalanche P-chain (for staking). 

### ISSUE THREAD

**Issue by MoonBoi9001** [airgap-it/airgap-vault#195]
Native staking occurs on the P-chain in the Avalanche network. The current offerings from airgap-it support the c-chain (evm) which is great for majority of defi however, since staking occurs on the p chain, any avalanche users who want to use airgap-it but also require being able to stake/delegate their tokens for the yield cannot seriously consider the airgap-it offering. It's a deep shame as I believe that many avalanche users would switch to airgap-it, especially now that ledger have demonstrated their incompetence.

Please add support for staking on avalanche.

**Comment by debeldami** [comment]
Firstly, there's no shame in not currently supporting Avalanche P-Chain, even though we will love to support it. To pursue a native integration for Avalanche, we would need some form of grant or support for integration. If you're aware of anyone who can assist with this, we'd greatly appreciate it if you could connect us with them. Thank you for your understanding.
