### ISSUE TITLE
Unable to enable the BIP39 Passphrase on the Android Vault version?

### ISSUE THREAD

**Issue by PRFinklemeister** [airgap-it/airgap-vault#198]
I select the password option when re-importing a secret (seed phrase) then in settings the option is still disabled with the message "This setting is disabled. Import your secret again to change it." Am I missing something? Resetting the vault had no effect. Using the same test seed phrase for this evaluation. 

EDIT: Perhaps it is my Motorola device: Moto G Power (2022)

Thanks in advance.

**Comment by AndreasGassmann** [comment]
Hi, thanks for reaching out.

The password you set during secret import is the encryption password, not the BIP39 passphrase. The encryption password is used to additionally require a password when unlocking the secure storage of your device to read the mnemonic.

The BIP39 passphrase can be set when adding an address, you can follow the guide here: https://support.airgap.it/guides/bip39/
