### ISSUE TITLE
Impossible to recover from mnemonic seed

### ISSUE THREAD

**Issue by sammy007** [airgap-it/airgap-vault#2]
I launched and generated mnemonic seed by Vault app, import seed does not work with it, the "IMPORT" button is just not active. I also tried with mnemonic seed generated by Trezor, we are using bip39, right?

The question is, did you test your own recovery procedure or I am doing something wrong? I assume I am right, because it's really hard to enter 24 words many times and make a mistake. Thanks.

**Update:** Vault must convert all words to lower case, just because every time you enter seed the first word starts from capital letter in this form. It's okay to assume that wallet will do that and its current behaviour causes a lot of inconveniences and confusion.

**Comment by sammy007** [comment]
Well, it was a typo.

**Comment by sammy007** [comment]
Vault must convert all words to lower case, just because every time you enter seed the first word starts from capital letter in this form. It's okay to assume that wallet will do that and its current behaviour causes a lot of inconveniences and confusion.

**Comment by pascuin** [comment]
Will close the issue to avoid confusion.
