### ISSUE TITLE
Can you create a Wagmi connector to support the AirGap Vault wallet?

### ISSUE THREAD

**Issue by saqing** [airgap-it/airgap-vault#200]
[Wagmi](https://wagmi.sh/core/getting-started) is a popular web3 library, and AirGap Vault is an excellent secure wallet. 
Can you create a Wagmi connector to support the AirGap Vault wallet?

**Comment by debeldami** [comment]
AirGap Vault is a completely offline signer, and it won't be appropriate to have a connector to it.  We already have WalletConnect in AirGap Wallet.
