### ISSUE TITLE
Will airgap-vault support stx (stx-i-stack) chain?

### ISSUE THREAD

**Issue by hlf20010508** [airgap-it/airgap-vault#202]
I've bought a lot `stx`, but I cannot send it into my wallet in airgap-vault.

Please take `stx` into consideration.

I would be really appreciated.

**Comment by debeldami** [comment]
We are enthusiastic about supporting Stacks (STX). If you have any contacts within the STX community who may be interested in contributing to the integration financially, we would greatly appreciate a connection.
