### ISSUE TITLE
airgap-vault crashes when generating new seed on a phone with no audio.

### ISSUE THREAD

**Issue by arcady-genkin** [airgap-it/airgap-vault#206]
I have a Pixel 2 phone that has issues with audio hardware (speaker and microphone are effectively unusable for unknown reason). The phone works 100% otherwise, so I figured it could be a good candidate for an AirGap vault.

AirGap vault can import pre-generated mnemonic phrase, but tapping on "Generate" results in the app closing immediately, with no error message. I'm pretty sure that this is because of the audio issues, because the exact same set up (same versions of everything) works well on another Pixel 2 that I have.

It would be nice if the app caught this exception and handled it gracefully. Ideally it would offer to generate without microphone support. Or at least output an error message "Cannot open audio device" or some such, and not crash.

**Comment by debeldami** [comment]
Hi, I just tried this on an iOS and Android device and I was able to generate a seed phrase
