### ISSUE TITLE
Tag v3.32.1 please

### ISSUE THREAD

**Issue by Giszmo** [airgap-it/airgap-vault#210]
On my phone I got version 3.32.1 from Google but I can't see any such tag.

**Comment by xrviv** [comment]
Just saw this as well.

**Comment by xrviv** [comment]
Thank you! 

We've noticed significant diffs on the latest build however. https://gitlab.com/walletscrutiny/walletScrutinyCom/-/merge_requests/740 

Time-willing, we would like to encourage you to assist us in getting AirGap Vault reproducible again.
