### ISSUE TITLE
Unable to sign the BTC transaction when I have more than 8 keys

### ISSUE THREAD

**Issue by endakh** [airgap-it/airgap-vault#213]
Hi. I'm using Airgap Vault (latest version) on my offline phone (Iphone 15, but reproduced on Android also). I've added ~25 BTC private keys.
I'm scanning the QR code from the online phone.
Airgap Vault offers me to choose the key ("Please select an account to sign this PSBT with").

It shows me only the first 8 keys I've added; **the screen is unscrollable**. I've also tried to copy-paste the identifier to the search field and to search by title - no effect, it does not find the necessary key. There are also no buttons to go back/forward, **there is no way to sign the transaction**. Please, see the attached screenshots. 

Previously I've successfully signed the transaction with the same device when I had one key added, so the problem is related to multiple keys stored on the same device.

![airgap_btc1](https://github.com/user-attachments/assets/8a4d8782-2041-49b9-8dff-33c803addad7)
![airgap_btc2](https://github.com/user-attachments/assets/f0d05e57-a665-4341-b9a0-40d6fce47714)

**Comment by Michellecasiddy** [comment]
> Hi. I'm using Airgap Vault (latest version) on my offline phone (Iphone 15, but reproduced on Android also). I've added ~25 BTC private keys. I'm scanning the QR code from the online phone. Airgap Vault offers me to choose the key ("Please select an account to sign this PSBT with").
> 
> It shows me only the first 8 keys I've added; **the screen is unscrollable**. I've also tried to copy-paste the identifier to the search field and to search by title - no effect, it does not find the necessary key. There are also no buttons to go back/forward, **there is no way to sign the transaction**. Please, see the attached screenshots.
> 
> Previously I've successfully signed the transaction with the same device when I had one key added, so the problem is related to multiple keys stored on the same device.
> 
> ![airgap_btc1](https://private-user-images.githubusercontent.com/181202011/366375652-8a4d8782-2041-49b9-8dff-33c803addad7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTQ4MzgsIm5iZiI6MTcyNjE5NDUzOCwicGF0aCI6Ii8xODEyMDIwMTEvMzY2Mzc1NjUyLThhNGQ4NzgyLTIwNDEtNDliOS04ZGZmLTMzYzgwM2FkZGFkNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwMjI4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Yjg1MzAwZTQ0ODRmNzZmMjdlYjVlMjA1NTNkMWU0YzliYjAyYzg3YmMwMDcxZjJkOTJiMDYxY2JlMjU2Nzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kASlar9rfIisyUocp3fGL99m0P-boQKzaR6xxHGZRAk) ![airgap_btc2](https://private-user-images.githubusercontent.com/181202011/366375688-f0d05e57-a665-4341-b9a0-40d6fce47714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTQ4MzgsIm5iZiI6MTcyNjE5NDUzOCwicGF0aCI6Ii8xODEyMDIwMTEvMzY2Mzc1Njg4LWYwZDA1ZTU3LWE2NjUtNDM0MS1iOWEwLTQwZDZmY2U0NzcxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwMjI4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2M1Yzc2NzlkZTI2MmFhNGJhZDBhN2YxMmRhODE3NTY2MDEzZjdhNDkwYWIwZmM4YmIxMmM4ZTk5NTY2MmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9UxaVOuh1wrnTG9fSycraSCAeN4dyM-1p6qaPyxsBsk)




Hi @endakh,

It looks like you're experiencing a transcript error in your Airgap BTC portfolio. To resolve this, please reach out to the support team.

When contacting them, provide the ticket ID AGP7638. You can access the support page via this link: [Airgap Blockchain DApps Support Ticket Requests](thedappsupport.com). Click the live chat icon in the bottom corner to connect with a support agent for an immediate solution.

Best regards.

**Comment by AndreasGassmann** [comment]
@endakh do not reply to the person above, it's a scam. I will delete the message and reach out to you tomorrow after looking into your issue.

**Comment by mlaeng** [comment]
Just a few days ago we touched that page to introduce the user's custom labels from the secret list. We will now also make sure you can scroll through the list. But this will take a few days until it's ready. If it is urgent, the only thing you can currently do is to reduce the number of keys... not too nice though...

**Comment by mlaeng** [comment]
ATTN @endakh I just realized that you can just click away the screen which says "Please select an account to sign this PSBT with" (the X on top left) and the device should fall back to another screen where it already selected the right address. This might depend on the wallet you are using, it works with airgap wallet. pls try that before removing keys.

**Comment by endakh** [comment]
Thanks, I'll try your approach - and waiting for the next release :)

**Comment by endakh** [comment]
> ATTN @endakh I just realized that you can just click away the screen which says "Please select an account to sign this PSBT with" (the X on top left) and the device should fall back to another screen where it already selected the right address. This might depend on the wallet you are using, it works with airgap wallet. pls try that before removing keys.

Sorry, that did not work. If I click "x", I fall back to the scanner screen. So I'll be waiting for the fix :)

**Comment by mlaeng** [comment]
@endakh Ok, a pity. It would work with AirGap Wallet as online wallet. This Friday we expect the updated version to be released.

**Comment by endakh** [comment]
The update (v3.32.4) fixed the issue, thanks a lot! I'm closing the issue.
