### ISSUE TITLE
QR Code size

### ISSUE THREAD

**Issue by RandoTTTest** [airgap-it/airgap-vault#215]
Hello,

I am using AirGap Vault with an HD webcam to read the code but the current QR size is not quite big enough to read properly.
Th QR setting of the android app seem to have no effect (reverted back when going in/out of the menu), no way to use lower density codes.
Taking a screenshot and extending the QR picture fullscreen works though.

Could you look into displaying the QR in full width of the screen and/or fixing the QR setting of the android app ?

Thank you

**Comment by debeldami** [comment]
Hi, @RandoTTTest . 

The QR code settings now persist in version 3.32.5 please check and let me know if this fixes the issue for you.

**Comment by RandoTTTest** [comment]
it works now. I was able to lower qr density successfully.
Thank you
