### ISSUE TITLE
[ERROR] Cannot load Cordova config.

### ISSUE THREAD

**Issue by vikramIde** [airgap-it/airgap-vault#22]
Hey Guys,

When I try to run build command

```ionic cordova platform run android```

I am getting error 

```
ERROR] Cannot load Cordova config.
        
        Could not find necessary file(s): config.xml, package.json.
        
        - ./config.xml
        - ./package.json
        
        You can re-add the Cordova integration with the following command: ionic integrations enable cordova --add
```

I am new to ionic I am guessing its a configuration file, which is missing in the project. 

Also i don't see that's added in the .gitignore file so perhaps its a required file

**Comment by AndreasGassmann** [comment]
Hi, this project has recently been migrated to `capacitor`, so `cordova` is not used anymore.

You should be able to do `npm run build` and `npx cap sync` and then run the native projects in Android Studio or XCode.

I'll leave this open as a reminder that we need to update the docs.
