### ISSUE TITLE
Problem in creating account from seed

### ISSUE THREAD

**Issue by vikramIde** [airgap-it/airgap-vault#27]
Hi guys,

I am having issue with generating new account from existing seed phrase.
**Error**
```
2020-09-01 10:12:32.201 13640-13640/it.airgap.vault E/Capacitor/Console: File: http://localhost/main.js - Line 3910 - Msg: TypeError: Cannot read property 'initStorage' of undefined
```
I have android studio 4 (the latest)

Previously i had compiled with android 3* versions and it had worked.

But this time it asked me to install version 4 and after that i started seeing the above issue.

some other capacitor plugins are not loading i think.

any thoughts in this ?

Thank you

**Comment by vikramIde** [comment]
Same issue with IOS build also

**Comment by AndreasGassmann** [comment]
I've never had this issue, It sounds like a problem with the secure storage.

Did you follow our build instructions?

Android: https://github.com/airgap-it/airgap-vault/blob/master/build/android/Dockerfile
iOS: https://github.com/airgap-it/airgap-vault/blob/master/.gitlab-ci.yml#L59

WalletScrutiny is able to independently reproduce our Vault build [see here](https://walletscrutiny.com/android/it.airgap.vault/), so if the apk from the store works, it must be something on your end.

**Comment by vikramIde** [comment]
@AndreasGassmann  I'll check the links you mentioned .

Yeah I was also kinda confused , as the downloaded version of APK from the store and it works.

Then somehow looks like my build process is doing something wrong.

Thank you

**Comment by vikramIde** [comment]
Hi @AndreasGassmann 

I am trying to build the APK with the given Dockerfile in the build/android folder.

I am able to build the container perfectly, But I am unsure where the out apk file will be located.

Like I see this is the command which copies the file

```
RUN cp /app/android/app/build/outputs/apk/release/app-release-unsigned.apk android-release-unsigned.apk

```
Is it copying src and destination both inside the container itself? or in my local machine?

Because I could not find the file in my local folder.

Please let me know if I am doing anything wrong.

**Comment by AndreasGassmann** [comment]
Yes the file is still inside the container in the root level.

You should be able to copy it out of the container using:

```
$ docker cp <container-id>:/android-release-unsigned.apk android-release-unsigned.apk
```
