### ISSUE TITLE
Please tag version 3.5.1 for reproducibility verification

### ISSUE THREAD

**Issue by Giszmo** [airgap-it/airgap-vault#32]
I just failed to verify the 3.5.1 release as there is no commit tagged as such. I will update [this review](https://walletscrutiny.com/android/it.airgap.vault/) once verification is possible again.

**Comment by Giszmo** [comment]
I failed again with the same version. Please see the [updated review](https://walletscrutiny.com/android/it.airgap.vault/).

**Comment by AndreasGassmann** [comment]
We will look into it.

**Comment by AndreasGassmann** [comment]
So I tried looking into what was going on and decided to set up the walletscrutiny build myself. To my surprise, after running your `test.sh`, this was the output:

```
Results:
appId:          it.airgap.vault
signer:         486381324d8669c80ca9b8c79d383dc972ec284227d65ebfe9e31cad5fd3f342
apkVersionName: 3.5.1
apkVersionCode: 23940
apkHash:        bcd00b91d962bcdab19fe6d506338c72d8ca047bd4eaa3d17d6d31ca924edea1

Diff:
Files /tmp/fromPlay_it.airgap.vault_23940/apktool.yml and /tmp/fromBuild_it.airgap.vault_23940/apktool.yml differ
Files /tmp/fromPlay_it.airgap.vault_23940/original/META-INF/MANIFEST.MF and /tmp/fromBuild_it.airgap.vault_23940/original/META-INF/MANIFEST.MF differ
Only in /tmp/fromPlay_it.airgap.vault_23940/original/META-INF: PAPERS.RSA
Only in /tmp/fromPlay_it.airgap.vault_23940/original/META-INF: PAPERS.SF

Revision, tag (and its signature):
object 32c980cd295c3976b5a4350cec30d8b10e00e650
type commit
tag v3.5.1
tagger Mike Godenzi <m.godenzi@papers.ch> 1605788380 +0100

version 3.5.1

Run a full
diff --recursive /tmp/fromPlay_it.airgap.vault_23940 /tmp/fromBuild_it.airgap.vault_23940
meld /tmp/fromPlay_it.airgap.vault_23940 /tmp/fromBuild_it.airgap.vault_23940
for more details.
```

So this looks like I was able to reproduce it? What I did was:
1. Set up a brand new Ubuntu 20 VM (with VMWare)
2. Installed dependencies `sudo apt update ; sudo apt install -y git docker.io disorderfs`
3. I don't really know how to properly download the APK from the play store, so I used this random website `https://apk.support/download-app/it.airgap.vault`.
4. I copied the downloaded .apk from the host to the VM
5. I ran `sudo ./test.sh vault.apk`

It looks like the `apkHash` doesn't match. But strangely, the `apkVersionName` and `apkVersionCode` do. What could the reason for that be? How do you usually download the apks from the play store?

**Comment by Giszmo** [comment]
The website provides a very slightly modified version of the apk but that's not the diff. According to diffoscope, the zip container differs but not the content. This is why your hash differs though.

I started a [project for apk collection](https://play.google.com/store/apps/details?id=com.walletscrutiny.android) as that is a tricky topic: As you know you can distribute a different app to different people. You could distribute a reproducible apk to Chile (where I am) and a wallet-stealer to the rest of the world. My app would detect updates of relevant apps and let the user upload the apk to the server and the idea is that it also switches off internet if a rogue update was detected but that's for the far future. Right now the app is not even uploading apks correctly or it's probably the server that's broken but I don't get to look into it between day job, baby and what you see of WalletScrutiny. Help wanted ;)

I use com.alphainventor.filemanager to backup apps and copy them to my pc then.

Good news: While writing this lengthy comment, a second run of the test script yielded a positive result. I would look into this anyway though, as some tool appears to not behave deterministically. I will update the website.
