### ISSUE TITLE
Electron: ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by YC** [airgap-it/airgap-vault#35]
Error:
![Screenshot_2021-01-18_22-11-21](https://user-images.githubusercontent.com/5828744/104909958-bb995f00-59dc-11eb-9ea7-a7d60d35547a.png)

Changing  `<base href="/" />` to `<base href="./" />` in `src/index.html` seem to fix some files but the `airgap-currency-symbols` still show `ERR_FILE_NOT_FOUND`. 

![Screenshot_2021-01-18_22-51-49](https://user-images.githubusercontent.com/5828744/104911959-c275a100-59df-11eb-9812-345a1d16f84a.png)

Commit 32c980cd295c3976b5a4350cec30d8b10e00e650
Electron v11.2.0

**Comment by AndreasGassmann** [comment]
How did you build it? Did you use `npm run electrum`?

**Comment by YC** [comment]
`npm run build` && `npm run electron`.

**Comment by AndreasGassmann** [comment]
I was able to reproduce the error. I'll let you know as soon as we have a solution.
