### ISSUE TITLE
Unstoppable Domains Support

### ISSUE THREAD

**Issue by trymeouteh** [airgap-it/airgap-vault#37]
I know some will prefer FIO or something else, but I would like to suggest adding support on integrating Unstoppable Domains

- Support .zil and .crypto addresses (Will need to add ZIL coin support for .zil domains)
- Ability to buy multiple unstoppable domains with crypto in the app 
- Ability to transfer multiple unstoppable domains to another address in the app
- Ability to add crypto addresses to multiple unstoppable domains in the app
- Ability to send crypto to an unstoppable domain address in the app

I prefer Unstoppable Domains since they are a one time purchase and you have it for life unlike FIO addresses, they are human readable and can help with adoption by being able to tell others were to send crypto to. Unstoppable domains can be used for other things like hosting IPFS stuff but I dont see a need for Airgap to support all of that, just for the ability to register, transfer domains and be able to easily accept crypto using a unstoppable domain.

**Comment by AndreasGassmann** [comment]
Domain support in the Vault is not possible, because it does not have network connectivity. An "address-book" like feature could be something to consider for the Vault in the future.

**Comment by trymeouteh** [comment]
Could this be done in the Wallet app (Not the vault)? Since the wallet app will be the app that will buy a domain, transfer a domain or add/remove addresses to a domain? And the wallet app could look up domain names for any attached crypto addresses.

**Comment by AndreasGassmann** [comment]
I responded to this here: https://github.com/airgap-it/airgap-wallet/issues/53

**Comment by trymeouteh** [comment]
ZIL support is not really need as much since Unstoppable Domains now supports up to 9 different domain extensions that are available on the Ethereum blockchain which are

.crypto
.coin
.wallet
.bitcoin
.x
.888
.nft
.dao
.blockchain
