### ISSUE TITLE
Support NIX Atomic Swaps

### ISSUE THREAD

**Issue by trymeouteh** [airgap-it/airgap-vault#38]
There are many ways to do private atomic swaps and transactions with non-private cryptos such as REN. I personally think NIX does it better and would like to suggest integrating NIX into the wallet for adding privacy to all crypto wallets and transactions for the users.

- Adding NIX token support (Will soon be a ERC20 token)
- Ability to have DEX atomic swaps using NIX protocol
- Integrate most or all privacy features offered by NIX in AirGap wallet (Ability to use BTC and other coins privately that are supported by NIX)

NIX is currently its own blockchain but is moving over onto Ethereum which I would imagine will make integrating NIX easier into airgap.

Flare Wallet (Wallet that uses NIX atomic swaps)
https://flarewallet.io/

NIX
https://nixplatform.io/

NIX moving onto Ethereum
https://nixplatform.medium.com/bringing-privacy-to-the-ever-expanding-world-of-ethereum-and-defi-28d1c0248d98

**Comment by AndreasGassmann** [comment]
Not applicable to the Vault.
