### ISSUE TITLE
Linux Mobile Vault App

### ISSUE THREAD

**Issue by trymeouteh** [airgap-it/airgap-vault#39]
Please create the vault app for linux phones to allow linux phone users like LibreM 5, Pinephone, Ubuntu Touch, etc users can use and enjoy AirGap.

Linux Mobile Wallet App
https://github.com/airgap-it/airgap-wallet/issues/50

**Comment by AndreasGassmann** [comment]
We can look into that at a later stage, but we would highly appreciate if someone could test this and create a PR.

**Comment by debeldami** [comment]
As Linux mobile phones are not as widely adopted as other operating systems like Android and iOS, we currently prioritize efforts on platforms with broader user bases. While we won't be investing time in this specific issue, we encourage you to explore and address it. will close this issue now.
