### ISSUE TITLE
Unable to sign transaction from VVault

### ISSUE THREAD

**Issue by asolomon15** [airgap-it/airgap-vault#4]
I'm running the Vault on a samsung galaxy tablet.  My issue is that I am unable to sign the transaction that was created from the mobile wallet.  I can successfully scan the transaction but when clicking the "sign transaction" button and verifying my identify, the signing verification window shows.   The application just hangs.    

anyone experience this ?

**Comment by pascuin** [comment]
Hey @asolomon15, could you let us know the exact device as well as your Android and AirGap Vault version?

Thanks!

**Comment by asolomon15** [comment]
Hi, 
Here's the information 
tablet Model: SAMSUNG-SM-T377A
Android version: 7.1.1
airgap vault version: 1.6.0 Code: 6774

I tried a different address and then it started working.  I got the feeling that there might be some issue with the address used.

**Comment by dschoeni** [comment]
After some digging together with @asolomon15 , we found out that the "scan from QR" also includes stuff like "bitcoin:" in the prepare screen. The prepareTx from bitcoin does not validate this and still works, but failed when signing the TX as we are then converting the TX.

**Comment by pascuin** [comment]
This has been fixed.
