### ISSUE TITLE
Release v3.7.0's sha256 seems to be incorrect

### ISSUE THREAD

**Issue by asdomingues** [airgap-it/airgap-vault#56]
Hi, hope everything's fine

I recently got to know the app and tried to install it from the [latest release page](https://github.com/airgap-it/airgap-vault/releases/tag/v3.7.0), but issuing `sha256sum airgap-vault-28519.apk` yielded
```sh
57c362a3508f1420007fe5d0867f889a9683f0b51d746ab20067fb9e90abbc2f  airgap-vault-28519.apk
```
instead of the expected
```sh
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  airgap-vault-28519.apk
```
Then I tried to verify the other two available downloads (the zip and tar ones) to check if the hash was from something else, but that wasn't the issue.

I ran through the same steps with the [previous version](https://github.com/airgap-it/airgap-vault/releases/tag/v3.6.2), and I was able to get the same hash for the APK as the one shown.

Am I missing something?

Thanks!

**Comment by AndreasGassmann** [comment]
You are right. I probably accidentally hashed the unsigned version. I updated the hash. BTW, it also matches the hash of the APK that was tested by walletscrutiny, so the APK that was uploaded is the correct one: https://walletscrutiny.com/android/it.airgap.vault/
