### ISSUE TITLE
Incompatibility with older Android versions (tested 2.0-4.4)

### ISSUE THREAD

**Issue by realdemayo** [airgap-it/airgap-vault#67]
Would it be possible to extend compatibility to those older devices?
What android version is required?

**Comment by ramast** [comment]
Android 5 is the absolute minimum and even then you still to make sure that system webview is up to date. Can update it using google play store

**Comment by AndreasGassmann** [comment]
Sorry for the late reply.

As @ramast said, the minimum required version is Android 5.

It might run on lower versions (4.x with updated webview), but we don't officially support it. The reason for this is that we use some APIs related to the secure storage that are only available on newer versions.

Android 5 was released in 2014. Assuming that phones that were 2 years old at that time got the update, that would make the Vault compatible with most phones released in the last 9 years.

We now have a dedicated page to track the compatibility of the Vault across different devices. Hopefully the community can help us extend the android list: https://support.airgap.it/airgap-vault/supported-devices/
