### ISSUE TITLE
Suggestion : Upgrade as ionic 4

### ISSUE THREAD

**Issue by sirius2013** [airgap-it/airgap-vault#7]
Hello Contributors
@pascuin @AndreasGassmann @dschoeni
I saw you contributed many things for this repo.

I am one of user of airgap wallet, I saw that is upgrade as ionic 4, but I think airgap-vault is not upgraded yet.

could I work for that?

Cheers

**Comment by AndreasGassmann** [comment]
Hi @sirius2013 

We have already started working on the upgrade of the Vault to Ionic 4. So we currently don't need any assistance there. If we ever have any issues, we'll contact you again. Thanks for offering your help!

**Comment by sirius2013** [comment]
ok, great!

**Comment by AndreasGassmann** [comment]
We may need help with the migration after all. Can you please contact me via email: andreas@airgap.it

**Comment by sirius2013** [comment]
okay, cool

**Comment by devotebest** [comment]
hello guys

**Comment by devotebest** [comment]
Please kill upwork account, so you will get refund money and need to send again.
