### ISSUE TITLE
Can't exit Vault (or Wallet) use back button.

### ISSUE THREAD

**Issue by Originalimoc** [airgap-it/airgap-vault#70]
Or All-screen gesture. Same thing.

**Comment by pjw65** [comment]
Back Button to exit still missing. 

Standard on Android first back displays a short message, that the next one (in a view seconds time) will exit. The second "back" exists.

**Comment by debeldami** [comment]
This issue no longer exist so I will close it.

**Comment by Originalimoc** [comment]
@debeldami Actually no? I still can not exit *Vault* using back *gesture* but can exit *Wallet*.
