### ISSUE TITLE
Add SegWit, PSBT and BC-UR v2 support

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/airgap-vault#73]
## Coinlib

- [x] To prepare a segwit/PSBT transaction, we need the masterFingerprint in the wallet. This should be added to all "share account" messages.
- [x] Add signing support for PSBTs
- [x] Add broadcast support for PSBTs
- [x] Extract data (eg. input and output, signatures) from PSBT so we can display it. (partially done)

## Apps

- [x] "prepareTransaction" in the Wallet must be called with masterFingerprint

## Other

- [ ] ~RBF (replace by fee) can now be configured, we need to add a UI for it~ (RBF can be done through watch-only wallets in the near future)

## Watch-only wallets

This will be addressed in a separate issue: https://github.com/airgap-it/airgap-vault/issues/105

**Comment by Originalimoc** [comment]
Cool, looking forward to it🌝

**Comment by AndreasGassmann** [comment]
AirGap now supports SegWit. Support for watch-only wallets has been moved to a new issue: https://github.com/airgap-it/airgap-vault/issues/105

In the next Vault update, we should have a working beta.
