### ISSUE TITLE
docker build does not terminate

### ISSUE THREAD

**Issue by Giszmo** [airgap-it/airgap-vault#77]
I just tried to reproduce the latest build and it got stuck on [this line](https://github.com/airgap-it/airgap-vault/blob/2c029f86025427dcb8762db7644da0fa57c9b661/build/android/Dockerfile#L65) I think:

    RUN echo y | $ANDROID_HOME/tools/bin/sdkmanager --update

To my surprise, hitting "y" worked. TIL: Docker build is interactive?

Either way, the approach that's more reliable is

    RUN yes | $ANDROID_HOME/tools/bin/sdkmanager --update

**Comment by AndreasGassmann** [comment]
It's weird that this is an issue for you. We run this on our CI and we never had any issues.

It looks like the second version works as well, so we'll probably change it if that works better for you.
