### ISSUE TITLE
Camera not opening in Android 8 when scanner is enabled - V 3.8.0

### ISSUE THREAD

**Issue by jaime0720** [airgap-it/airgap-vault#79]
I installed version 3.8.0 on a Samsung with Android 8, everything works perfect except by the camera, when I tap into scanner option the camera is not opening. Tried with version 3.7.0 and camera works. Any idea? Thanks

**Comment by benweet** [comment]
Same here on android (8 on Umidigi Z2) and iOS (11.4.1 on iphone 6S). I can't click the scanner button and sign any transaction.

**Comment by benweet** [comment]
Works good after upgrading to iOS 14 👍

**Comment by giz02** [comment]
Same. Wow. But open and unassigned since August 11... Is this project still alive?

**Comment by AndreasGassmann** [comment]
> I installed version 3.8.0 on a Samsung with Android 8, everything works perfect except by the camera, when I tap into scanner option the camera is not opening. Tried with version 3.7.0 and camera works. Any idea? Thanks

Does the latest version work for you? We made a few changes to the native code that hopefully addresses your issue.

> Same. Wow. But open and unassigned since August 11... Is this project still alive?

If this issue is that important to you, feel free to create a PR to fix it instead of writing useless comments.

**Comment by dim0xff** [comment]
> Does the latest version work for you? We made a few changes to the native code that hopefully addresses your issue.
> ...
> If this issue is that important to you, feel free to create a PR to fix it instead of writing useless comments.
>

Hi!
I faced with this issue on my old phone with Android 7. Just built app from sources and checked it: v3.15.0 has the problem.

As I see the problem comes from dependency `"@zxing/ngx-scanner": "3.1.3"` (ngx-scanner version was increased in update https://github.com/airgap-it/airgap-vault/compare/v3.7.0...v3.8.0).

After some playing around with [package.json](https://github.com/airgap-it/airgap-vault/blob/v3.15.0/package.json) scanner works well on my Android7 with these deps:
```
    "@zxing/browser": "0.0.10",
    "@zxing/library": "0.18.6",
    "@zxing/ngx-scanner": "3.3.0",
```

It solves issue with my device but probably it needs further testing with other devices/OS versions.

**Comment by AndreasGassmann** [comment]
Thanks @dim0xff for investigating. We'll look into this.

**Comment by tarasau** [comment]
Hi @AndreasGassmann, face that issue on iphone 7, ios 12.1.4. Permission for camera is added. App version is 3.17.0.
In the local error history I see: `Uncaught (in promise): TypeError: undefined is not an object (evaluating 'Qt[vi]') `
Also for this version/device I had an issue with display of secret, with local error: `Uncaught (in promise): Error: Keychain (-106): Item not found`
Is it possible to test via simulator for this device/version or could you please suggest the version of ios on which this features will work properly?
