### ISSUE TITLE
Can't create account with linux built

### ISSUE THREAD

**Issue by climu** [airgap-it/airgap-vault#93]
Using AirGap Vault Linux 1.0.0 from this [build](https://github.com/airgap-it/airgap-vault/actions/runs/1169558901) on linux Mint 20.

I can generate or import a secret successfully.

I canot create an account:
1. In this windows I select any coin
![image](https://user-images.githubusercontent.com/2648653/131914422-a9aefd87-5ae4-4038-9998-0c0e4f29b1d4.png)
2. I click create. A popup appear: 
![image](https://user-images.githubusercontent.com/2648653/131914601-fed19d85-7b61-4503-b670-53ce1456dbf7.png)
3. I am back to same windows as 1.
4. I go back and see no currency: 
![image](https://user-images.githubusercontent.com/2648653/131914841-b00e9ef5-6d8c-4474-b07f-60b21e203a92.png)

I tried to sync with a wallet but the captcha was not scanned.

**Comment by AndreasGassmann** [comment]
Hi, thanks for opening this issue. I can confirm that the MacOS app from the github actions build also doesn't work (same behaviour as you describe).

I will look into this asap.

**Comment by AndreasGassmann** [comment]
I'm currently not on the computer so I can't try it, but would you mind trying an older version to see if it's a regression in the latest version? For example this one: https://github.com/airgap-it/airgap-vault/actions/runs/1088366043

**Comment by climu** [comment]
Thank you for your answer.
I was able to create an account using the build you just link.

**Comment by AndreasGassmann** [comment]
Thanks. That means there is a regression in the latest version. We will look into it.
