### ISSUE TITLE
Airgap missing from walletscrutiny.com reproducible list

### ISSUE THREAD

**Issue by themsay** [airgap-it/airgap-vault#94]
Hi,

After installing Airgap Vault/Wallet in my Android phone when it appeared in walletscrutiny.com reproducible list, I notice this morning that is now missing after the last update.

My question is Airgap vault/wallet still fully open source and *reproducible*?

Thanks!

**Comment by Originalimoc** [comment]
Fix pending. Wait next release.

**Comment by AndreasGassmann** [comment]
The current release does not seem to be reproducible. We will release 3.9.1 shortly to fix this: https://github.com/airgap-it/airgap-vault/issues/91

I'm closing this issue as a duplicate.
