### ISSUE TITLE
[Request] Arch Linux AUR

### ISSUE THREAD

**Issue by Pakrohk** [airgap-it/airgap-vault#99]
Hi, I checked the Android version of your software, it was really amazing.

1- I decided to check the desktop version as well, I am using the Arch Linux distribution, for GNU/Linux you do not have a version other than AppImage and this causes inconsistencies in the system, If possible, please add [aur](https://aur.archlinux.org/), [rpm](https://rpm.org/), etc to your collection for available options.

2 - I do most of my transactions using [tron](https://github.com/tronprotocol) currency, ‌ how can I add this currency to your wallet ?

forgive me for not knowing English well.

**Comment by AndreasGassmann** [comment]
1. I'm not very familiar with the Linux platform. If you know how, it would be great if you could create a PR that adds the desired builds here: https://github.com/airgap-it/airgap-vault/blob/master/electron/package.json#L13 and https://github.com/airgap-it/airgap-vault/blob/master/.github/workflows/build.yml#L245

2. Our wallet does not support tron at the moment. To add new coins, we usually work with the teams behind those coins. If you know anyone that could help us with that, please talk to them and tell them to reach out to us :).

**Comment by andrew-m-higgs** [comment]
Hi guys

I played around with this a bit. I assume we would need to add  `"target": ["AppImage", "deb", "rpm", "snap"]` (in package.json) the problem is the build produces an app with just a blank page. It shows the version as '0.0.1' which I assume is incorrect. Perhaps the targets could be split into separate scripts rather than building all of them in one.

I am no electron expert but I will be glad to look at ways to fix this if anyone has any pointers I can look into.

**Comment by ALipAkrohk** [comment]
>     1. I'm not very familiar with the Linux platform. If you know how, it would be great if you could create a PR that adds the desired builds here: https://github.com/airgap-it/airgap-vault/blob/master/electron/package.json#L13 and https://github.com/airgap-it/airgap-vault/blob/master/.github/workflows/build.yml#L245
> 
>     2. Our wallet does not support tron at the moment. To add new coins, we usually work with the teams behind those coins. If you know anyone that could help us with that, please talk to them and tell them to reach out to us :).

Thanks for your answer, I will try to help.
